version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    restart: always

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs:rw
    restart: always

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    networks:
      - proxy-tier
    
  app:
    build:
      context: app
      # Setting team edition or change UID/GID
      args:
        - edition=team
        #- PUID=1000
        #- PGID=1000
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=$MM_DB_USERNAME
      - MM_PASSWORD=$MM_DB_PASSWORD
      - MM_DBNAME=$MM_DB_NAME
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json
      - VIRTUAL_HOST=$MM_VIRTUAL_HOST
      - VIRTUAL_PORT=8000
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=$MM_TLS_HOST
      - LETSENCRYPT_EMAIL=$MM_TLS_MAIL
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy
